version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: apidb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d apidb"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata fixtures/main/cats.json && python manage.py loaddata fixtures/main/prod.json && python manage.py loaddata fixtures/main/admin.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

